### ISSUE TITLE
Add regression line and info to plot in visualization tab

### ISSUE THREAD

**Issue by pommevilla** [pommevilla/germs_shiny_project#5]
## Tasks

- [x] Add a line of best fit to the plot in the visualization tab (`geom_smooth`)
- [x] Somewhere on the plot, use `annotate` to write what the correlation coefficient is
- [ ] Add a button on the side bar to toggle the confidence interval on `geom_smooth`
